### ISSUE TITLE
Doesn't work with beta pre-release

### ISSUE THREAD

**Issue by jcayzac** [omichelsen/compare-versions#1]
```
> compare('1.0.0', '1.0.0-beta')
0
```

**Comment by omichelsen** [comment]
That is true, I hadn't considered the pre-release and metadata format of semver.

I have added support for this in the latest release [v1.1.0](https://github.com/omichelsen/compare-versions/releases/tag/v1.1.0).

**Comment by no-more** [comment]
Hi,

Thanks for this great tool,

I have another issue with beta pre-release. 0.1.1-beta.9 is returned bigger than 0.1.1-beta.13

This seems to be the way you compare p1 and p2 as string. This works for alpha<beta and form single digits prerelease (0.1.1-beta.5 < 0.1.1-beta.9) but not for multi digit prerelease.

Those version number were genereted with semver so I think they are valid.

**Comment by no-more** [comment]
Here is an updated version, I haven't tried other version number, but at least this fix this use case. This needs to be more deeply tested before merging

https://github.com/omichelsen/compare-versions/compare/master...no-more:patch-1

**Comment by omichelsen** [comment]
Thanks for the info, I have published a fix as [v2.0.2](https://github.com/omichelsen/compare-versions/releases/tag/v2.0.2).
