### ISSUE TITLE
angular.js version error 

### ISSUE THREAD

**Issue by lushijie** [omichelsen/compare-versions#11]
angular.js   1.0.0rc12 version Invalid argument not valid semver Error.

var semver = /^v?(?:0|[1-9]\d_)(.(?:[x_]|0|[1-9]\d_)(.(?:[x_]|0|[1-9]\d_)(?:-_[\da-z-]+(?:.[\da-z-]+)_)?(?:+[\da-z-]+(?:.[\da-z-]+)_)?)?)?$/i;
//var semver = /^v?(?:0|[1-9]\d_)(.(?:[x_]|0|[1-9]\d_)(.(?:[x_]|0|[1-9]\d_)(?:-[\da-z-]+(?:.[\da-z-]+)_)?(?:+[\da-z-]+(?:.[\da-z-]+)_)?)?)?$/i;
var patch = /-_([0-9A-Za-z-.]+)/;
//var patch = /-([0-9A-Za-z-.]+)/;

'-' should be optional .

**Comment by omichelsen** [comment]
The '-' to separate metadata is not optional according to the [semver spec #9](https://semver.org/#spec-item-9).

**Comment by lushijie** [comment]
thank you
