### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by mgyatso** [omichelsen/compare-versions#13]
**Uncaught ReferenceError: require is not defined**

Attempting to set 'var compareVersions = require('compare-versions');' in my main js file.

What steps do I need to take to get 'require' defined?

**Comment by omichelsen** [comment]
If you are trying to run it in a browser without using browserify or webpack, you can just include the script and then start using `compareVersions` directly with out the `require` statement.

**Comment by mgyatso** [comment]
Thank you. So if my array is called '$product_versions' then my code should be:

```
var versions_sorted = $product_versions.sort(compareVersions);
return versions_sorted;
```

Correct?

**Comment by omichelsen** [comment]
Yes that seems correct.

**Comment by mgyatso** [comment]
Thank you.
