### ISSUE TITLE
Regex not matching Chrome version

### ISSUE THREAD

**Issue by Merraclius** [omichelsen/compare-versions#16]
Current regex not matching Chrome version (65.0.3325.181) as result method validate throw Error "Invalid argument not valid semver"

**Comment by omichelsen** [comment]
Yes Chrome is not using the semver standard. This also means that each position in [their numbering](https://www.chromium.org/developers/version-numbers) means something slightly different than in semver. 

Not sure if it is possible to treat them the same without side effects.

**Comment by Merraclius** [comment]
If I'm understand correctly the 4th number in version is **BRANCH_BRANCH_BUILD**.
It's build using the same rule as **BRANCH_BUILD**. 
I just fixed regex for **semver** and **patch** (sign _-_ was marked as optional) and it's work fine for me.

**Comment by omichelsen** [comment]
I have released an update to support this. Take it for spin.
