### ISSUE TITLE
versions sort: 1.0.0-SNAPSHOT is greater then 1.0.0-RELASE?

### ISSUE THREAD

**Issue by wzlee** [omichelsen/compare-versions#27]
![image](https://user-images.githubusercontent.com/4182865/55934549-8090c600-5c63-11e9-894a-2f6981773feb.png)
What happended to it?

**Comment by omichelsen** [comment]
Pre-releases are sorted alphabetically which means that R<S=RELEASE<SNAPSHOT according to semver spec [#11](https://semver.org/#spec-item-11).
