### ISSUE TITLE
Feature Request: allow specifying to ignore subpatch/patch/minor level for comparison

### ISSUE THREAD

**Issue by ComFreek** [omichelsen/compare-versions#30]
E.g. in pseudocode: `compareVersions('1.0.0.123', '1.0.0.125', '=', ignoreSubPatch = true) == true`

**Comment by omichelsen** [comment]
This could also be achieved by stripping this out patches from the versions before comparing them (e.g. with `version.replace(...)`). This might be easier since you know the situation the code is used in better than a generic library can?

Otherwise I would welcome a PR with a suggestion.
