### ISSUE TITLE
Subversions is only limited to 4

### ISSUE THREAD

**Issue by rramanadham** [omichelsen/compare-versions#32]
I have a version that is 9.2.0.4.0 and it fails as the the semver can only take upto 4 subversions.

//copied the below from compare-versions/index.js
 var semver = /^v?(?:\d+)(\.(?:[x*]|\d+)(\.(?:[x*]|\d+)(\.(?:[x*]|\d+))?(?:-[\da-z\-]+(?:\.[\da-z\-]+)*)?(?:\+[\da-z\-]+(?:\.[\da-z\-]+)*)?)?)?$/i;

Can this be dynamic allowing any number of sub versions?

**Comment by omichelsen** [comment]
This library is trying to follow the semver standard (with a few extensions). Semver only allows 3 numbers and we've extended it to cover Chrome versions which use 4. I guess it could be extended to allow infinite but I'm wary about the complexity implications.
