### ISSUE TITLE
human readable is not usable with es6 import

### ISSUE THREAD

**Issue by rogerkerse** [omichelsen/compare-versions#33]
import compareVersions from 'compare-versions'

compareVersions.compare(......) <-- "compareVersions.default.compare is not a function"

**Comment by omichelsen** [comment]
Can you share some more info on what your build tools look like; babel, webpack, typescript etc.?

**Comment by omichelsen** [comment]
This works for me with TypeScript:
```js
import compareVersions from "compare-versions";
console.log(compareVersions.compare("1.0", "2.0", ">"));
```
