### ISSUE TITLE
Unexpected comparison result

### ISSUE THREAD

**Issue by Eugene-Lytvynov** [omichelsen/compare-versions#34]
hi. 
we try use: compareVersions('5.0.0', '5.0.0-1'). but it return 1. why? Logically it is new build of v.5. it must be -1.
Best Regard, Eugene

**Comment by omichelsen** [comment]
Everything after the hyphen is considered a pre-release version and always considered _less than_ a release version. If you compare two pre-release versions like `5.0.0-1` and `5.0.0-2` it will return `-1`.
