### ISSUE TITLE
Expose validate function?

### ISSUE THREAD

**Issue by m-mohr** [omichelsen/compare-versions#37]
Thanks for this useful library. Is there any chance to get the validate function exposed, too? I'd like to use it and at the moment I need to copy the code as it is not exported. Something like compareVersions.validate() maybe?

I would be willing to do a PR if it has a chance to get merged and released soon.

**Comment by omichelsen** [comment]
That sounds good to me, please feel free to make a PR.

**Comment by m-mohr** [comment]
Did so, see #38

**Comment by omichelsen** [comment]
Thank you, I have merged and released!

**Comment by m-mohr** [comment]
Thank you!
