### ISSUE TITLE
Comparison with prior art

### ISSUE THREAD

**Issue by dandv** [omichelsen/compare-versions#4]
Wondering what the rationale was for creating this library, when @substack's [semver-compare](https://github.com/substack/semver-compare) already existed. A comparison helping users pick between the two would be nice. Thanks!

**Comment by omichelsen** [comment]
Sure, here goes a short list of the main differences/reasons for creating [compare-versions](https://github.com/omichelsen/compare-versions):
- added UMD support
- added Bower support
- support comparing versions with different number of digits, e.g. `compare('1.1.1', '1')`
- support comparing pre-release versions, e.g. `compare('1.0.0-alpha', '1.0.0-beta')` and comparing to non-pre-releases `compare('1.0.0', '1.0.0-alpha')`

The latter two are part of the full semver standard and not supported by semver-compare.
