### ISSUE TITLE
Support metadata comparison

### ISSUE THREAD

**Issue by DavidHenri008** [omichelsen/compare-versions#40]
It would be nice to have an option to support metadata comparison, as a pure string.

For version like 1.2.3+444.3

Thanks.

**Comment by omichelsen** [comment]
This is supported, e.g. 1.2.3-pre.2 > 1.2.3-pre.1.

I think the problem is that you are using `+` as a metadata separator. The `+` means "build data" and should not figure into the comparison (https://semver.org/#spec-item-10). Your version should be 1.2.3-444.3 to be compared.

**Comment by DavidHenri008** [comment]
@omichelsen As you mentioned the '''+''' means build data and even if it is not supposed to be part of comparison, it would be nice, via an option, to consider it.

**Comment by omichelsen** [comment]
Since this would go against the semver spec and possibly lead to breaking behavior I am not planning to include this.
