### ISSUE TITLE
Supporting caret and tilde (^ ~)

### ISSUE THREAD

**Issue by Jaaap** [omichelsen/compare-versions#43]
Have you ever considered supporting the caret and tilde operators?
https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json

Edit: this would not make sense for sorting and comparing, it would only be for some sort of `isMatch("1.1.2", "^1.1.0")` function

**Comment by omichelsen** [comment]
I have started the [range PR](https://github.com/omichelsen/compare-versions/pull/47) adding a `satisfies(version, match)` function. Feel free to give feedback.
