### ISSUE TITLE
Much smaller alternative version

### ISSUE THREAD

**Issue by jimmywarting** [omichelsen/compare-versions#45]
Just wanted to share this:

Was looking for an alternative dependency free solution
came up with this:

```js
let version = [...process.version.match(/v(\d+)\.(\d+)\.(\d+)/)] // [ 'v16.4.2', '16', '4', '2' ]
version[0] = 0
version = new Uint32Array(new Uint8Array(version).buffer)[0]

if (version < 34541056) {
  // node version is lower than 14.15.2
}
```

**Comment by jsamr** [comment]
@jimmywarting Doesn't seem like your implementation supports pre-releases!

``` js
compareVersions.compare("6.0.0-beta.2", "6.0.0-beta.1", ">");
// true
```

**Comment by jimmywarting** [comment]
nope, it dose not, but then later i found this localeCompare+numric solution that was much better: 
```js
const isGreater = (a, b) => a.localeCompare(b, undefined, { numeric: true }) === 1
```
https://stackoverflow.com/questions/55466274/simplify-semver-version-compare-logic/55466325#55466325


That can also work for pre-releases

**Comment by jsamr** [comment]
@jimmywarting Nice!

**Comment by jsamr** [comment]
@jimmywarting Actually, not working when comparing a pre-release with a release with the same MAJOR.MINOR.PATCH

```js
"6.0.0-alpha.1".localeCompare("6.0.0", "en", {numeric: true});
// 1 (should be -1)
compareVersions.compare("6.0.0-alpha.1", "6.0.0", ">")
// false
```

**Comment by omichelsen** [comment]
It's a really nice way of doing it, didn't know about this feature. I tried running it through the test suite, and unfortunately it seems there's a few scenarios it doesn't support:
- Different length version strings: 1.0.0.0 = 1, 1.0.0.0 = 1.0, 1.0.0.0 = 1.0.0
- Prefixes: v1.2.3.4 = 01.2.3.4
- Metadata: 1.4.0-build.3928 = 1.4.0-build.3928+sha.a8d9d4f, 1.0.0+a-a = 1.0.0+a-b

This could of course be fixed in other ways, but it then ends up taking a few more lines of code anyway :)

**Comment by omichelsen** [comment]
I've started a branch with a full ESM version of this library, where I'm using the `localeCompare` to shorten the code a bit too. Let me know what you think: https://github.com/omichelsen/compare-versions/compare/esm?expand=1

I have noticed that the runtime of using `localeCompare` is pretty horrendous though. On my local machine the current implementation runs 100000 comparisons in ~88ms and the new one takes ~900ms(!)

So I made a new esm branch just refactoring the code a bit for readability and that maintains the fast performance: https://github.com/omichelsen/compare-versions/compare/esm-fast?expand=1

**Comment by omichelsen** [comment]
The new ESM version has been merged and is smaller and faster than before, and much much faster than `localeCompare`: https://jsbench.me/tpkvd0wm8s/1.

**Comment by jimmywarting** [comment]
ty, but I'm gona stick to using a slower builtin `localeCompare` version
rather prefer some one liner dependency free version. I don't need to run version comparison 100000 times. 
i.m.o it's not something that needs to be optimized. 

if it would have been a video encoder/deecoder then by all means yes, optimize the hell out of it :P
