### ISSUE TITLE
Unexpected behaviour change in Version 4.0.1

### ISSUE THREAD

**Issue by WolfWalter** [omichelsen/compare-versions#48]
After upgrading to Version 4.0.1 the result of a version comparison changed. A change in behaviour was not mentioned in the changelog. Here is a example: 
https://codepen.io/wolfwalter/pen/dyzqZNK

The result for `compare('3.3.3','3.x.x','<')` was `false` in 3.6.0 and is `true` in 4.0.1

**Comment by omichelsen** [comment]
Thanks for reporting, this is an oversight not covered by our unit tests. I will try and fix...

**Comment by omichelsen** [comment]
Made a PR #49 to fix. Comments are welcome, will merge soon.
