### ISSUE TITLE
Difference between API exported via CommonJS and ESM

### ISSUE THREAD

**Issue by krzysztof-kwiecinski** [omichelsen/compare-versions#51]
In version `4.0.0` the ES6 module version of script was added (there is a new file `index.mjs`). However, it exports different API then exported by `index.js`. A good practice is to export the same APIs both for ESM and CJS. Otherwise, it can cause problems.

Example:
- Webpack prefers the code from `.mjs`
- Jest prefers the code from `.js`
- `compareVersions.validate` is a function in `.js`, and is undefined in `.mjs`
- Code works correctly in Jest, but fails in the browser

The exported APIs should be the same.

**Comment by omichelsen** [comment]
I have released v4.1.3 to fix this. Please let me know if it works for you.

**Comment by krzysztof-kwiecinski** [comment]
Thanks! The commit looks good, I'll check that with my code on Monday

**Comment by krzysztof-kwiecinski** [comment]
I forgot to close this issue... It's working perfectly. Thank you very much @omichelsen !
