### ISSUE TITLE
Source maps are broken on v5

### ISSUE THREAD

**Issue by durasj** [omichelsen/compare-versions#61]
This is obvious when using [source-map-loader](https://webpack.js.org/loaders/source-map-loader/):

```Failed to parse source map from '<projectPath>/node_modules/compare-versions/src/index.ts' file: Error: ENOENT: no such file or directory, open '<projectPath>/node_modules/compare-versions/src/index.ts'```.

Source `src/index.ts` is referenced in `esm/index.js.map`:

![image](https://user-images.githubusercontent.com/1062898/186937397-894fade5-2aad-4978-9403-6ea32f790621.png)

I would love to help but I'm tight on time at the moment. Hopefully, this will at least help you catch this sooner.

Thanks!

**Comment by omichelsen** [comment]
Thanks for the quick heads up. I’ll get it fixed. 

Edit: v5.0.1 now includes the source files for source maps.

**Comment by durasj** [comment]
Wow, thanks! :) I can confirm it works correctly now.
