### ISSUE TITLE
The expected output of `satisfies` is different between v4 and v5

### ISSUE THREAD

**Issue by rqbazan** [omichelsen/compare-versions#64]
Hi there, I've recently noticed that the output of `satisfies` is different between v4 and v5:

REPL: https://npm.runkit.com/compare-versions

## v5

```js
var compareVersions = require("compare-versions@5.0.1")

compareVersions.satisfies('9.0.0', '<6.22.0') // false
```

## v4

```js
var compareVersions = require("compare-versions@4.1.3")

compareVersions.satisfies('9.0.0', '<6.22.0') // true
```

Why is that? It is actually expected? 🤔

**Comment by omichelsen** [comment]
This was a bug in v4 which was fixed by v5 (see #58).
