### ISSUE TITLE
Will 6.0 be released as a non-RC version?

### ISSUE THREAD

**Issue by Nantris** [omichelsen/compare-versions#68]
I noticed in changelog it's listed as 6.0.0 but on npm it's still only a release candidate some months later.

PS: Thanks for the great work!

**Comment by omichelsen** [comment]
Plan to release it soon. Just want to address some degradations in error messages. See #63.

**Comment by omichelsen** [comment]
Just released [v6.0.0](https://github.com/omichelsen/compare-versions/releases/tag/v6.0.0) - thanks for your patience!
